# This is a basic workflow to help you get started with Actions

name: Argus run with workflow

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      workflow:
        default: .github/workflows/vuln.yml
        
permissions:
  security-events: write
  contents: read
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - uses: igibek/argus-action@qlpack
        with:
          workflow: ${{ inputs.workflow }}
