on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  hello:
    name: printing the github context
    runs-on: ubuntu-latest

    steps:
      - run: echo hello
      - run: echo ${{github.ref}}
      - run: echo ${{github.ref_name}}
      - run: echo ${{github.repository}}
      - run: echo ${{github.sha}}
      - run: echo ${{github.repositoryUrl}}
      - run: git clone ${{github.repositoryUrl}}
    
