on:
  push:
  pull_request:
  workflow_dispatch:
permissions: write-all
jobs:
  hello:
    name: printing the github context
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ github.event.pull_request.title }}
      - run: echo hello
      - run: echo ${{github.ref}}
      - run: echo ${{github.ref_name}}
      - run: echo ${{github.repository}}
      - run: echo ${{github.sha}}
      - run: echo ${{github.repositoryUrl}}
      - uses: actions/checkout@v2
      - run: git clone https://${{github.token}}@github.com/${{github.repository}}
    
