on:
  push:
  pull_request:
  workflow_dispatch:
permissions: write-all
jobs:
  hello:
    name: printing the github context
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ github.event.pull_request.title }}
      - run: echo hello
      - run: echo ${{github.ref}}
      - run: echo ${{github.ref_name}}
      - run: echo ${{github.repository}}
      - run: echo ${{github.sha}}
      - run: echo ${{github.repositoryUrl}}
      # - uses: actions/checkout@v2
      - name: setting up the auth
        run: \
          git config --global --name-only --get-regexp core\.sshCommand
          git submodule foreach --recursive sh -c "git config --global --name-only --get-regexp 'core\.sshCommand' && git config --global --unset-all 'core.sshCommand' || :"
          git config --global --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
          git submodule foreach --recursive sh -c "git config --global --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --global --unset-all 'http.https://github.com/.extraheader' || :"
          git config --global http.https://github.com/.extraheader AUTHORIZATION:basic ${{github.token}}
      - run: git clone ${{github.repositoryUrl}}
      - run: git clone https://${{github.token}}@github.com/${{github.repository}}
    
